Retrieving logs for app jdbcpoc in org tito-vakyam-dev / space development as tito.mathews@gmail.com...

   2018-10-13T07:37:05.28-0600 [APP/PROC/WEB/0] OUT 2018-10-13 13:37:05.280  INFO 16 --- [nio-8080-exec-8] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring FrameworkServlet 'dispatcherServlet'
   2018-10-13T07:37:05.28-0600 [APP/PROC/WEB/0] OUT 2018-10-13 13:37:05.280  INFO 16 --- [nio-8080-exec-8] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServlet': initialization started
   2018-10-13T07:37:05.32-0600 [APP/PROC/WEB/0] OUT 2018-10-13 13:37:05.328  INFO 16 --- [nio-8080-exec-8] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServlet': initialization completed in 48 ms
   2018-10-13T07:37:05.81-0600 [APP/PROC/WEB/0] OUT 2018-10-13 13:37:05.815  INFO 16 --- [io-8080-exec-10] c.netflix.config.DynamicPropertyFactory  : DynamicPropertyFactory is initialized with configuration sources: com.netflix.config.ConcurrentCompositeConfiguration@35ff1eee
   2018-10-13T07:37:06.78-0600 [APP/PROC/WEB/0] OUT LOGGER::In Primary..
   2018-10-13T07:37:06.79-0600 [APP/PROC/WEB/0] OUT LOGGER::In Primary..
   2018-10-13T07:37:06.79-0600 [APP/PROC/WEB/0] OUT 2018-10-13 13:37:06.796  WARN 16 --- [x-primaryPool-1] o.a.tomcat.jdbc.pool.ConnectionPool      : maxIdle is larger than maxActive, setting maxIdle to: 4
   2018-10-13T07:37:07.10-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured TIMEOUT
   2018-10-13T07:37:07.10-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured TIMEOUT
   2018-10-13T07:37:07.20-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured TIMEOUT
   2018-10-13T07:37:07.20-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured TIMEOUT
   2018-10-13T07:37:07.28-0600 [APP/PROC/WEB/0] OUT LOGGER::In Secondary..null
   2018-10-13T07:37:07.28-0600 [APP/PROC/WEB/0] OUT LOGGER::In Secondary..null
   2018-10-13T07:37:07.32-0600 [APP/PROC/WEB/0] OUT LOGGER::In Secondary..null
   2018-10-13T07:37:07.32-0600 [APP/PROC/WEB/0] OUT LOGGER::In Secondary..null
   2018-10-13T07:37:12.99-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured SUCCESS
   2018-10-13T07:37:13.00-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured SUCCESS
   2018-10-13T07:37:13.00-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured SUCCESS
   2018-10-13T07:37:13.17-0600 [RTR/6] OUT jdbcpoc.cfapps.io - [2018-10-13T13:37:05.723+0000] "GET /delay?d1=5&d2=5 HTTP/1.1" 200 0 17 "-" "Apache-HttpClient/4.5.3 (Java/1.8.0_152)" "10.10.66.112:7276" "10.10.149.182:61070" x_forwarded_for:"24.11.122.135, 10.10.66.112" x_forwarded_proto:"http" vcap_request_id:"904601fe-ad27-4842-6e44-36da8763872b" response_time:7.456057166 app_id:"94d62bb6-bcdd-4f80-b701-37b1cee68def" app_index:"0" x_b3_traceid:"e90b97300555dad6" x_b3_spanid:"e90b97300555dad6" x_b3_parentspanid:"-"
   2018-10-13T07:37:13.17-0600 [RTR/6] OUT 
   2018-10-13T07:37:13.18-0600 [RTR/0] OUT jdbcpoc.cfapps.io - [2018-10-13T13:37:05.525+0000] "GET /delay?d1=5&d2=5 HTTP/1.1" 200 0 17 "-" "Apache-HttpClient/4.5.3 (Java/1.8.0_152)" "10.10.66.112:10634" "10.10.149.182:61070" x_forwarded_for:"24.11.122.135, 10.10.66.112" x_forwarded_proto:"http" vcap_request_id:"27cfb293-2d83-4294-7eef-63b9dbb582d3" response_time:7.656431295 app_id:"94d62bb6-bcdd-4f80-b701-37b1cee68def" app_index:"0" x_b3_traceid:"508bbe202b90199a" x_b3_spanid:"508bbe202b90199a" x_b3_parentspanid:"-"
   2018-10-13T07:37:13.18-0600 [RTR/0] OUT 
   2018-10-13T07:37:13.18-0600 [RTR/9] OUT jdbcpoc.cfapps.io - [2018-10-13T13:37:05.329+0000] "GET /delay?d1=5&d2=5 HTTP/1.1" 200 0 17 "-" "Apache-HttpClient/4.5.3 (Java/1.8.0_152)" "10.10.66.112:17272" "10.10.149.182:61070" x_forwarded_for:"24.11.122.135, 10.10.66.112" x_forwarded_proto:"http" vcap_request_id:"ba4227ef-95c1-4762-71aa-7e7b769f496a" response_time:7.854643493 app_id:"94d62bb6-bcdd-4f80-b701-37b1cee68def" app_index:"0" x_b3_traceid:"bd31061614bd633b" x_b3_spanid:"bd31061614bd633b" x_b3_parentspanid:"-"
   2018-10-13T07:37:13.18-0600 [RTR/9] OUT 
   2018-10-13T07:37:13.18-0600 [RTR/3] OUT jdbcpoc.cfapps.io - [2018-10-13T13:37:05.922+0000] "GET /delay?d1=5&d2=5 HTTP/1.1" 200 0 17 "-" "Apache-HttpClient/4.5.3 (Java/1.8.0_152)" "10.10.66.112:56736" "10.10.149.182:61070" x_forwarded_for:"24.11.122.135, 10.10.66.112" x_forwarded_proto:"http" vcap_request_id:"c371d220-c8e9-45d0-4cfe-25f55e863db0" response_time:7.261990446 app_id:"94d62bb6-bcdd-4f80-b701-37b1cee68def" app_index:"0" x_b3_traceid:"808a207f759d5315" x_b3_spanid:"808a207f759d5315" x_b3_parentspanid:"-"
   2018-10-13T07:37:13.18-0600 [RTR/3] OUT 
   2018-10-13T07:37:13.00-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured SUCCESS
   2018-10-13T07:37:13.00-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured FALLBACK_SUCCESS
   2018-10-13T07:37:13.00-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured FALLBACK_SUCCESS
   2018-10-13T07:37:13.00-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured FALLBACK_SUCCESS
   2018-10-13T07:37:13.00-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured TIMEOUT
   2018-10-13T07:37:13.00-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured FALLBACK_SUCCESS
   2018-10-13T07:37:13.18-0600 [APP/PROC/WEB/0] OUT LOGGER::In Secondary..null
   2018-10-13T07:37:13.36-0600 [APP/PROC/WEB/0] OUT LOGGER::In Primary..
   2018-10-13T07:37:13.55-0600 [RTR/1] OUT jdbcpoc.cfapps.io - [2018-10-13T13:37:05.217+0000] "GET /delay?d1=5&d2=5 HTTP/1.1" 200 0 52 "-" "Apache-HttpClient/4.5.3 (Java/1.8.0_152)" "10.10.66.112:33726" "10.10.149.182:61070" x_forwarded_for:"24.11.122.135, 10.10.66.112" x_forwarded_proto:"http" vcap_request_id:"e3349997-90ca-415f-75ec-f3e419ecb3b4" response_time:8.338498656 app_id:"94d62bb6-bcdd-4f80-b701-37b1cee68def" app_index:"0" x_b3_traceid:"718da0de6f4dc009" x_b3_spanid:"718da0de6f4dc009" x_b3_parentspanid:"-"
   2018-10-13T07:37:13.55-0600 [RTR/1] OUT 
   2018-10-13T07:37:13.54-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured TIMEOUT
   2018-10-13T07:37:13.54-0600 [APP/PROC/WEB/0] OUT LOGGER::InfinalCall..null
   2018-10-13T07:37:13.54-0600 [APP/PROC/WEB/0] OUT 2018-10-13 13:37:13.542 ERROR 16 --- [ HystrixTimer-2] c.n.h.c.javanica.command.GenericCommand  : failed to process fallback is the method: 'finalCall'. 
   2018-10-13T07:37:13.54-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured FALLBACK_FAILURE
   2018-10-13T07:37:13.54-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured EXCEPTION_THROWN
   2018-10-13T07:37:13.54-0600 [APP/PROC/WEB/0] OUT 2018-10-13 13:37:13.545 ERROR 16 --- [ HystrixTimer-4] c.n.h.c.javanica.command.GenericCommand  : failed to process fallback: 'secondaryCall'. secondaryCall fallback is a hystrix command. exception: 'class java.util.concurrent.TimeoutException' occurred in fallback wasn't ignored.
   2018-10-13T07:37:13.54-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured FALLBACK_FAILURE
   2018-10-13T07:37:13.54-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured EXCEPTION_THROWN
   2018-10-13T07:37:13.55-0600 [APP/PROC/WEB/0] ERR com.netflix.hystrix.exception.HystrixRuntimeException: primaryCall timed-out and fallback failed.
   2018-10-13T07:37:13.56-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$22.call(AbstractCommand.java:825)
   2018-10-13T07:37:13.56-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$22.call(AbstractCommand.java:804)
   2018-10-13T07:37:13.56-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:140)
   2018-10-13T07:37:13.56-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:13.56-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:13.56-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$DeprecatedOnFallbackHookApplication$1.onError(AbstractCommand.java:1472)
   2018-10-13T07:37:13.56-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$FallbackHookApplication$1.onError(AbstractCommand.java:1397)
   2018-10-13T07:37:13.56-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:13.56-0600 [APP/PROC/WEB/0] ERR 	at rx.observers.Subscribers$5.onError(Subscribers.java:230)
   2018-10-13T07:37:13.56-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:44)
   2018-10-13T07:37:13.56-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:28)
   2018-10-13T07:37:13.56-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:13.56-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
   2018-10-13T07:37:13.56-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
   2018-10-13T07:37:13.56-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:13.56-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   2018-10-13T07:37:13.56-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   2018-10-13T07:37:13.56-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   2018-10-13T07:37:13.56-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   2018-10-13T07:37:13.56-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   2018-10-13T07:37:13.56-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   2018-10-13T07:37:13.56-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:13.56-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   2018-10-13T07:37:13.56-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   2018-10-13T07:37:13.56-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:13.56-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   2018-10-13T07:37:13.56-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   2018-10-13T07:37:13.56-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   2018-10-13T07:37:13.56-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   2018-10-13T07:37:13.56-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:13.56-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   2018-10-13T07:37:13.56-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   2018-10-13T07:37:13.56-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   2018-10-13T07:37:13.56-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   2018-10-13T07:37:13.56-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:13.56-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:142)
   2018-10-13T07:37:13.56-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:13.56-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:13.56-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator$1$1.run(AbstractCommand.java:1154)
   2018-10-13T07:37:13.56-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable$1.call(HystrixContextRunnable.java:45)
   2018-10-13T07:37:13.56-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable$1.call(HystrixContextRunnable.java:41)
   2018-10-13T07:37:13.56-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable.run(HystrixContextRunnable.java:61)
   2018-10-13T07:37:13.56-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator$1.tick(AbstractCommand.java:1159)
   2018-10-13T07:37:13.56-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.util.HystrixTimer$1.run(HystrixTimer.java:99)
   2018-10-13T07:37:13.56-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
   2018-10-13T07:37:13.56-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
   2018-10-13T07:37:13.56-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
   2018-10-13T07:37:13.56-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
   2018-10-13T07:37:13.56-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   2018-10-13T07:37:13.56-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   2018-10-13T07:37:13.56-0600 [APP/PROC/WEB/0] ERR 	at java.lang.Thread.run(Thread.java:748)
   2018-10-13T07:37:13.56-0600 [APP/PROC/WEB/0] ERR Caused by: java.util.concurrent.TimeoutException
   2018-10-13T07:37:13.56-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand.handleTimeoutViaFallback(AbstractCommand.java:997)
   2018-10-13T07:37:13.56-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand.access$500(AbstractCommand.java:60)
   2018-10-13T07:37:13.56-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$12.call(AbstractCommand.java:610)
   2018-10-13T07:37:13.56-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$12.call(AbstractCommand.java:601)
   2018-10-13T07:37:13.56-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:140)
   2018-10-13T07:37:13.56-0600 [APP/PROC/WEB/0] ERR 	... 15 more
   2018-10-13T07:37:13.86-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured TIMEOUT
   2018-10-13T07:37:13.87-0600 [APP/PROC/WEB/0] OUT LOGGER::In Secondary..null
   2018-10-13T07:37:13.89-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured TIMEOUT
   2018-10-13T07:37:13.89-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured TIMEOUT
   2018-10-13T07:37:13.89-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured TIMEOUT
   2018-10-13T07:37:13.89-0600 [APP/PROC/WEB/0] OUT LOGGER::In Secondary..null
   2018-10-13T07:37:13.89-0600 [APP/PROC/WEB/0] OUT LOGGER::In Secondary..null
   2018-10-13T07:37:13.89-0600 [APP/PROC/WEB/0] OUT LOGGER::In Secondary..null
   2018-10-13T07:37:18.06-0600 [APP/PROC/WEB/0] OUT LOGGER::In Primary..
   2018-10-13T07:37:18.88-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured SUCCESS
   2018-10-13T07:37:18.90-0600 [RTR/3] OUT jdbcpoc.cfapps.io - [2018-10-13T13:37:13.355+0000] "GET /delay?d1=5&d2=5 HTTP/1.1" 200 0 17 "-" "Apache-HttpClient/4.5.3 (Java/1.8.0_152)" "10.10.66.112:56736" "10.10.149.182:61070" x_forwarded_for:"24.11.122.135, 10.10.66.112" x_forwarded_proto:"http" vcap_request_id:"9e5c800c-1da8-484b-4649-90a0d6d1aff8" response_time:5.544705701 app_id:"94d62bb6-bcdd-4f80-b701-37b1cee68def" app_index:"0" x_b3_traceid:"3d1ec66166b90f98" x_b3_spanid:"3d1ec66166b90f98" x_b3_parentspanid:"-"
   2018-10-13T07:37:18.90-0600 [RTR/3] OUT 
   2018-10-13T07:37:18.88-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured FALLBACK_SUCCESS
   2018-10-13T07:37:18.88-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured TIMEOUT
   2018-10-13T07:37:18.91-0600 [APP/PROC/WEB/0] OUT LOGGER::In Secondary..null
   2018-10-13T07:37:19.15-0600 [APP/PROC/WEB/0] OUT LOGGER::In Primary..
   2018-10-13T07:37:23.08-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured SUCCESS
   2018-10-13T07:37:23.08-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured FALLBACK_SUCCESS
   2018-10-13T07:37:23.09-0600 [RTR/4] OUT jdbcpoc.cfapps.io - [2018-10-13T13:37:13.357+0000] "GET /delay?d1=5&d2=5 HTTP/1.1" 200 0 17 "-" "Apache-HttpClient/4.5.3 (Java/1.8.0_152)" "10.10.66.112:32864" "10.10.149.182:61070" x_forwarded_for:"24.11.122.135, 10.10.66.112" x_forwarded_proto:"http" vcap_request_id:"fc36c86b-11bb-473b-5c27-2b985d132717" response_time:9.733539634 app_id:"94d62bb6-bcdd-4f80-b701-37b1cee68def" app_index:"0" x_b3_traceid:"771ee683eeac924c" x_b3_spanid:"771ee683eeac924c" x_b3_parentspanid:"-"
   2018-10-13T07:37:23.09-0600 [RTR/4] OUT 
   2018-10-13T07:37:23.13-0600 [RTR/7] OUT jdbcpoc.cfapps.io - [2018-10-13T13:37:13.359+0000] "GET /delay?d1=5&d2=5 HTTP/1.1" 200 0 52 "-" "Apache-HttpClient/4.5.3 (Java/1.8.0_152)" "10.10.66.112:27832" "10.10.149.182:61070" x_forwarded_for:"24.11.122.135, 10.10.66.112" x_forwarded_proto:"http" vcap_request_id:"0ac80133-cc0f-4f8b-4431-78a2f137d1f7" response_time:9.780115176 app_id:"94d62bb6-bcdd-4f80-b701-37b1cee68def" app_index:"0" x_b3_traceid:"7d22701d9ba6790c" x_b3_spanid:"7d22701d9ba6790c" x_b3_parentspanid:"-"
   2018-10-13T07:37:23.13-0600 [RTR/7] OUT 
   2018-10-13T07:37:23.14-0600 [RTR/1] OUT jdbcpoc.cfapps.io - [2018-10-13T13:37:13.729+0000] "GET /delay?d1=5&d2=5 HTTP/1.1" 200 0 52 "-" "Apache-HttpClient/4.5.3 (Java/1.8.0_152)" "10.10.66.112:33726" "10.10.149.182:61070" x_forwarded_for:"24.11.122.135, 10.10.66.112" x_forwarded_proto:"http" vcap_request_id:"a1dfefd7-92af-470f-6ae4-1637f6805fb3" response_time:9.417297611 app_id:"94d62bb6-bcdd-4f80-b701-37b1cee68def" app_index:"0" x_b3_traceid:"2c2ffb826e56c239" x_b3_spanid:"2c2ffb826e56c239" x_b3_parentspanid:"-"
   2018-10-13T07:37:23.14-0600 [RTR/1] OUT 
   2018-10-13T07:37:23.08-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured TIMEOUT
   2018-10-13T07:37:23.08-0600 [APP/PROC/WEB/0] OUT LOGGER::InfinalCall..null
   2018-10-13T07:37:23.09-0600 [APP/PROC/WEB/0] OUT 2018-10-13 13:37:23.089 ERROR 16 --- [ HystrixTimer-1] c.n.h.c.javanica.command.GenericCommand  : failed to process fallback is the method: 'finalCall'. 
   2018-10-13T07:37:23.09-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured FALLBACK_FAILURE
   2018-10-13T07:37:23.09-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured EXCEPTION_THROWN
   2018-10-13T07:37:23.09-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured TIMEOUT
   2018-10-13T07:37:23.09-0600 [APP/PROC/WEB/0] OUT 2018-10-13 13:37:23.091 ERROR 16 --- [ HystrixTimer-2] c.n.h.c.javanica.command.GenericCommand  : failed to process fallback: 'secondaryCall'. secondaryCall fallback is a hystrix command. exception: 'class java.util.concurrent.TimeoutException' occurred in fallback wasn't ignored.
   2018-10-13T07:37:23.09-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured FALLBACK_FAILURE
   2018-10-13T07:37:23.09-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured EXCEPTION_THROWN
   2018-10-13T07:37:23.09-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured TIMEOUT
   2018-10-13T07:37:23.09-0600 [APP/PROC/WEB/0] OUT LOGGER::InfinalCall..null
   2018-10-13T07:37:23.09-0600 [APP/PROC/WEB/0] OUT 2018-10-13 13:37:23.095 ERROR 16 --- [ HystrixTimer-1] c.n.h.c.javanica.command.GenericCommand  : failed to process fallback is the method: 'finalCall'. 
   2018-10-13T07:37:23.09-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured FALLBACK_FAILURE
   2018-10-13T07:37:23.09-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured EXCEPTION_THROWN
   2018-10-13T07:37:23.09-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured TIMEOUT
   2018-10-13T07:37:23.09-0600 [APP/PROC/WEB/0] OUT 2018-10-13 13:37:23.098 ERROR 16 --- [ HystrixTimer-4] c.n.h.c.javanica.command.GenericCommand  : failed to process fallback: 'secondaryCall'. secondaryCall fallback is a hystrix command. exception: 'class java.util.concurrent.TimeoutException' occurred in fallback wasn't ignored.
   2018-10-13T07:37:23.09-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured FALLBACK_FAILURE
   2018-10-13T07:37:23.09-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured EXCEPTION_THROWN
   2018-10-13T07:37:23.10-0600 [APP/PROC/WEB/0] ERR com.netflix.hystrix.exception.HystrixRuntimeException: primaryCall timed-out and fallback failed.
   2018-10-13T07:37:23.10-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$22.call(AbstractCommand.java:825)
   2018-10-13T07:37:23.10-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$22.call(AbstractCommand.java:804)
   2018-10-13T07:37:23.10-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:140)
   2018-10-13T07:37:23.10-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:23.10-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:23.10-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$DeprecatedOnFallbackHookApplication$1.onError(AbstractCommand.java:1472)
   2018-10-13T07:37:23.10-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$FallbackHookApplication$1.onError(AbstractCommand.java:1397)
   2018-10-13T07:37:23.10-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:23.10-0600 [APP/PROC/WEB/0] ERR 	at rx.observers.Subscribers$5.onError(Subscribers.java:230)
   2018-10-13T07:37:23.10-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:44)
   2018-10-13T07:37:23.10-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:28)
   2018-10-13T07:37:23.10-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:23.10-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
   2018-10-13T07:37:23.10-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
   2018-10-13T07:37:23.10-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:23.10-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   2018-10-13T07:37:23.10-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   2018-10-13T07:37:23.10-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   2018-10-13T07:37:23.10-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   2018-10-13T07:37:23.10-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   2018-10-13T07:37:23.10-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   2018-10-13T07:37:23.10-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:23.10-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   2018-10-13T07:37:23.10-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   2018-10-13T07:37:23.10-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:23.10-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   2018-10-13T07:37:23.10-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   2018-10-13T07:37:23.10-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   2018-10-13T07:37:23.10-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   2018-10-13T07:37:23.10-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:23.10-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   2018-10-13T07:37:23.10-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   2018-10-13T07:37:23.10-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   2018-10-13T07:37:23.10-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   2018-10-13T07:37:23.10-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:23.10-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:142)
   2018-10-13T07:37:23.10-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:23.10-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:23.11-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator$1$1.run(AbstractCommand.java:1154)
   2018-10-13T07:37:23.11-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable$1.call(HystrixContextRunnable.java:45)
   2018-10-13T07:37:23.11-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable$1.call(HystrixContextRunnable.java:41)
   2018-10-13T07:37:23.11-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable.run(HystrixContextRunnable.java:61)
   2018-10-13T07:37:23.11-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator$1.tick(AbstractCommand.java:1159)
   2018-10-13T07:37:23.11-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.util.HystrixTimer$1.run(HystrixTimer.java:99)
   2018-10-13T07:37:23.11-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
   2018-10-13T07:37:23.11-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
   2018-10-13T07:37:23.11-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
   2018-10-13T07:37:23.11-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
   2018-10-13T07:37:23.11-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   2018-10-13T07:37:23.11-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   2018-10-13T07:37:23.11-0600 [APP/PROC/WEB/0] ERR 	at java.lang.Thread.run(Thread.java:748)
   2018-10-13T07:37:23.11-0600 [APP/PROC/WEB/0] OUT LOGGER::InfinalCall..null
   2018-10-13T07:37:23.11-0600 [APP/PROC/WEB/0] OUT 2018-10-13 13:37:23.113 ERROR 16 --- [ HystrixTimer-2] c.n.h.c.javanica.command.GenericCommand  : failed to process fallback is the method: 'finalCall'. 
   2018-10-13T07:37:23.11-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured FALLBACK_FAILURE
   2018-10-13T07:37:23.11-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured EXCEPTION_THROWN
   2018-10-13T07:37:23.11-0600 [APP/PROC/WEB/0] OUT LOGGER::In Secondary..null
   2018-10-13T07:37:23.11-0600 [APP/PROC/WEB/0] OUT 2018-10-13 13:37:23.118 ERROR 16 --- [ HystrixTimer-3] c.n.h.c.javanica.command.GenericCommand  : failed to process fallback: 'secondaryCall'. secondaryCall fallback is a hystrix command. exception: 'class java.util.concurrent.TimeoutException' occurred in fallback wasn't ignored.
   2018-10-13T07:37:23.11-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured FALLBACK_FAILURE
   2018-10-13T07:37:23.11-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured EXCEPTION_THROWN
   2018-10-13T07:37:23.11-0600 [APP/PROC/WEB/0] ERR Caused by: java.util.concurrent.TimeoutException
   2018-10-13T07:37:23.11-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand.handleTimeoutViaFallback(AbstractCommand.java:997)
   2018-10-13T07:37:23.11-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand.access$500(AbstractCommand.java:60)
   2018-10-13T07:37:23.11-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$12.call(AbstractCommand.java:610)
   2018-10-13T07:37:23.11-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$12.call(AbstractCommand.java:601)
   2018-10-13T07:37:23.12-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:140)
   2018-10-13T07:37:23.12-0600 [APP/PROC/WEB/0] ERR 	... 15 more
   2018-10-13T07:37:23.12-0600 [APP/PROC/WEB/0] ERR com.netflix.hystrix.exception.HystrixRuntimeException: primaryCall timed-out and fallback failed.
   2018-10-13T07:37:23.12-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$22.call(AbstractCommand.java:825)
   2018-10-13T07:37:23.12-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$22.call(AbstractCommand.java:804)
   2018-10-13T07:37:23.12-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:140)
   2018-10-13T07:37:23.12-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:23.12-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:23.12-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$DeprecatedOnFallbackHookApplication$1.onError(AbstractCommand.java:1472)
   2018-10-13T07:37:23.12-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$FallbackHookApplication$1.onError(AbstractCommand.java:1397)
   2018-10-13T07:37:23.12-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:23.12-0600 [APP/PROC/WEB/0] ERR 	at rx.observers.Subscribers$5.onError(Subscribers.java:230)
   2018-10-13T07:37:23.12-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:44)
   2018-10-13T07:37:23.12-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:28)
   2018-10-13T07:37:23.12-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:23.12-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
   2018-10-13T07:37:23.12-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
   2018-10-13T07:37:23.12-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:23.12-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   2018-10-13T07:37:23.12-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   2018-10-13T07:37:23.12-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   2018-10-13T07:37:23.12-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   2018-10-13T07:37:23.12-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   2018-10-13T07:37:23.12-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   2018-10-13T07:37:23.12-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:23.12-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   2018-10-13T07:37:23.12-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   2018-10-13T07:37:23.13-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:23.13-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   2018-10-13T07:37:23.13-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   2018-10-13T07:37:23.13-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   2018-10-13T07:37:23.13-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   2018-10-13T07:37:23.13-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:23.13-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   2018-10-13T07:37:23.13-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   2018-10-13T07:37:23.13-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   2018-10-13T07:37:23.13-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   2018-10-13T07:37:23.13-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:23.13-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:142)
   2018-10-13T07:37:23.13-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:23.13-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:23.13-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator$1$1.run(AbstractCommand.java:1154)
   2018-10-13T07:37:23.13-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable$1.call(HystrixContextRunnable.java:45)
   2018-10-13T07:37:23.13-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable$1.call(HystrixContextRunnable.java:41)
   2018-10-13T07:37:23.13-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable.run(HystrixContextRunnable.java:61)
   2018-10-13T07:37:23.13-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator$1.tick(AbstractCommand.java:1159)
   2018-10-13T07:37:23.13-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.util.HystrixTimer$1.run(HystrixTimer.java:99)
   2018-10-13T07:37:23.13-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
   2018-10-13T07:37:23.13-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
   2018-10-13T07:37:23.13-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
   2018-10-13T07:37:23.13-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
   2018-10-13T07:37:23.13-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   2018-10-13T07:37:23.13-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   2018-10-13T07:37:23.13-0600 [APP/PROC/WEB/0] ERR 	at java.lang.Thread.run(Thread.java:748)
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR Caused by: java.util.concurrent.TimeoutException
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand.handleTimeoutViaFallback(AbstractCommand.java:997)
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand.access$500(AbstractCommand.java:60)
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$12.call(AbstractCommand.java:610)
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$12.call(AbstractCommand.java:601)
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:140)
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR 	... 15 more
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR com.netflix.hystrix.exception.HystrixRuntimeException: primaryCall timed-out and fallback failed.
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$22.call(AbstractCommand.java:825)
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$22.call(AbstractCommand.java:804)
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:140)
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$DeprecatedOnFallbackHookApplication$1.onError(AbstractCommand.java:1472)
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$FallbackHookApplication$1.onError(AbstractCommand.java:1397)
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR 	at rx.observers.Subscribers$5.onError(Subscribers.java:230)
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:44)
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:28)
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:142)
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator$1$1.run(AbstractCommand.java:1154)
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable$1.call(HystrixContextRunnable.java:45)
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable$1.call(HystrixContextRunnable.java:41)
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable.run(HystrixContextRunnable.java:61)
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator$1.tick(AbstractCommand.java:1159)
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.util.HystrixTimer$1.run(HystrixTimer.java:99)
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR 	at java.lang.Thread.run(Thread.java:748)
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR Caused by: java.util.concurrent.TimeoutException
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand.handleTimeoutViaFallback(AbstractCommand.java:997)
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand.access$500(AbstractCommand.java:60)
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$12.call(AbstractCommand.java:610)
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$12.call(AbstractCommand.java:601)
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:140)
   2018-10-13T07:37:23.14-0600 [APP/PROC/WEB/0] ERR 	... 15 more
   2018-10-13T07:37:23.15-0600 [RTR/11] OUT jdbcpoc.cfapps.io - [2018-10-13T13:37:13.365+0000] "GET /delay?d1=5&d2=5 HTTP/1.1" 200 0 52 "-" "Apache-HttpClient/4.5.3 (Java/1.8.0_152)" "10.10.66.112:2108" "10.10.149.182:61070" x_forwarded_for:"24.11.122.135, 10.10.66.112" x_forwarded_proto:"http" vcap_request_id:"6387312c-5b47-4022-7c80-c543774eb275" response_time:9.784882165 app_id:"94d62bb6-bcdd-4f80-b701-37b1cee68def" app_index:"0" x_b3_traceid:"0333f47fb9cb8699" x_b3_spanid:"0333f47fb9cb8699" x_b3_parentspanid:"-"
   2018-10-13T07:37:23.15-0600 [RTR/11] OUT 
   2018-10-13T07:37:23.35-0600 [APP/PROC/WEB/0] OUT LOGGER::In Primary..
   2018-10-13T07:37:23.61-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured TIMEOUT
   2018-10-13T07:37:23.62-0600 [RTR/9] OUT jdbcpoc.cfapps.io - [2018-10-13T13:37:19.140+0000] "GET /delay?d1=5&d2=5 HTTP/1.1" 200 0 52 "-" "Apache-HttpClient/4.5.3 (Java/1.8.0_152)" "10.10.66.112:18476" "10.10.149.182:61070" x_forwarded_for:"24.11.122.135, 10.10.66.112" x_forwarded_proto:"http" vcap_request_id:"f181bc25-b226-4fe5-751e-93292e835bd5" response_time:4.484712127 app_id:"94d62bb6-bcdd-4f80-b701-37b1cee68def" app_index:"0" x_b3_traceid:"d006d7192e03a0e2" x_b3_spanid:"d006d7192e03a0e2" x_b3_parentspanid:"-"
   2018-10-13T07:37:23.62-0600 [RTR/9] OUT 
   2018-10-13T07:37:23.61-0600 [APP/PROC/WEB/0] OUT LOGGER::InfinalCall..null
   2018-10-13T07:37:23.61-0600 [APP/PROC/WEB/0] OUT 2018-10-13 13:37:23.616 ERROR 16 --- [ HystrixTimer-4] c.n.h.c.javanica.command.GenericCommand  : failed to process fallback is the method: 'finalCall'. 
   2018-10-13T07:37:23.61-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured FALLBACK_FAILURE
   2018-10-13T07:37:23.61-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured EXCEPTION_THROWN
   2018-10-13T07:37:23.61-0600 [APP/PROC/WEB/0] OUT 2018-10-13 13:37:23.617 ERROR 16 --- [ HystrixTimer-1] c.n.h.c.javanica.command.GenericCommand  : failed to process fallback: 'secondaryCall'. secondaryCall fallback is a hystrix command. exception: 'class java.util.concurrent.TimeoutException' occurred in fallback wasn't ignored.
   2018-10-13T07:37:23.61-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured FALLBACK_FAILURE
   2018-10-13T07:37:23.61-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured EXCEPTION_THROWN
   2018-10-13T07:37:23.61-0600 [APP/PROC/WEB/0] ERR com.netflix.hystrix.exception.HystrixRuntimeException: primaryCall timed-out and fallback failed.
   2018-10-13T07:37:23.61-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$22.call(AbstractCommand.java:825)
   2018-10-13T07:37:23.61-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$22.call(AbstractCommand.java:804)
   2018-10-13T07:37:23.61-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:140)
   2018-10-13T07:37:23.61-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:23.61-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:23.61-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$DeprecatedOnFallbackHookApplication$1.onError(AbstractCommand.java:1472)
   2018-10-13T07:37:23.61-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$FallbackHookApplication$1.onError(AbstractCommand.java:1397)
   2018-10-13T07:37:23.61-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:23.61-0600 [APP/PROC/WEB/0] ERR 	at rx.observers.Subscribers$5.onError(Subscribers.java:230)
   2018-10-13T07:37:23.61-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:44)
   2018-10-13T07:37:23.61-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:28)
   2018-10-13T07:37:23.61-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:23.61-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
   2018-10-13T07:37:23.61-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
   2018-10-13T07:37:23.61-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:23.61-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   2018-10-13T07:37:23.61-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   2018-10-13T07:37:23.61-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   2018-10-13T07:37:23.61-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   2018-10-13T07:37:23.61-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   2018-10-13T07:37:23.61-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   2018-10-13T07:37:23.62-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:23.62-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   2018-10-13T07:37:23.62-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   2018-10-13T07:37:23.62-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:23.62-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   2018-10-13T07:37:23.62-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   2018-10-13T07:37:23.62-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   2018-10-13T07:37:23.62-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   2018-10-13T07:37:23.62-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:23.62-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   2018-10-13T07:37:23.62-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   2018-10-13T07:37:23.62-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   2018-10-13T07:37:23.62-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   2018-10-13T07:37:23.62-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:23.62-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:142)
   2018-10-13T07:37:23.62-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:23.62-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:23.62-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator$1$1.run(AbstractCommand.java:1154)
   2018-10-13T07:37:23.62-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable$1.call(HystrixContextRunnable.java:45)
   2018-10-13T07:37:23.62-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable$1.call(HystrixContextRunnable.java:41)
   2018-10-13T07:37:23.62-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable.run(HystrixContextRunnable.java:61)
   2018-10-13T07:37:23.62-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator$1.tick(AbstractCommand.java:1159)
   2018-10-13T07:37:23.62-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.util.HystrixTimer$1.run(HystrixTimer.java:99)
   2018-10-13T07:37:23.62-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
   2018-10-13T07:37:23.62-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
   2018-10-13T07:37:23.62-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
   2018-10-13T07:37:23.62-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
   2018-10-13T07:37:23.62-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   2018-10-13T07:37:23.62-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   2018-10-13T07:37:23.62-0600 [APP/PROC/WEB/0] ERR 	at java.lang.Thread.run(Thread.java:748)
   2018-10-13T07:37:23.62-0600 [APP/PROC/WEB/0] ERR Caused by: java.util.concurrent.TimeoutException
   2018-10-13T07:37:23.62-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand.handleTimeoutViaFallback(AbstractCommand.java:997)
   2018-10-13T07:37:23.62-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand.access$500(AbstractCommand.java:60)
   2018-10-13T07:37:23.62-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$12.call(AbstractCommand.java:610)
   2018-10-13T07:37:23.62-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$12.call(AbstractCommand.java:601)
   2018-10-13T07:37:23.62-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:140)
   2018-10-13T07:37:23.62-0600 [APP/PROC/WEB/0] ERR 	... 15 more
   2018-10-13T07:37:23.85-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured TIMEOUT
   2018-10-13T07:37:23.85-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured TIMEOUT
   2018-10-13T07:37:23.85-0600 [APP/PROC/WEB/0] OUT LOGGER::In Secondary..null
   2018-10-13T07:37:23.85-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured TIMEOUT
   2018-10-13T07:37:23.85-0600 [APP/PROC/WEB/0] OUT LOGGER::In Secondary..null
   2018-10-13T07:37:23.85-0600 [APP/PROC/WEB/0] OUT LOGGER::In Secondary..null
   2018-10-13T07:37:23.88-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured TIMEOUT
   2018-10-13T07:37:23.88-0600 [APP/PROC/WEB/0] OUT LOGGER::In Secondary..null
   2018-10-13T07:37:23.95-0600 [APP/PROC/WEB/0] OUT LOGGER::In Primary..
   2018-10-13T07:37:28.91-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured SUCCESS
   2018-10-13T07:37:28.91-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured FALLBACK_SUCCESS
   2018-10-13T07:37:28.91-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured TIMEOUT
   2018-10-13T07:37:28.91-0600 [APP/PROC/WEB/0] OUT LOGGER::InfinalCall..null
   2018-10-13T07:37:28.92-0600 [APP/PROC/WEB/0] OUT 2018-10-13 13:37:28.919 ERROR 16 --- [ HystrixTimer-3] c.n.h.c.javanica.command.GenericCommand  : failed to process fallback is the method: 'finalCall'. 
   2018-10-13T07:37:28.92-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured FALLBACK_FAILURE
   2018-10-13T07:37:28.92-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured EXCEPTION_THROWN
   2018-10-13T07:37:28.92-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured TIMEOUT
   2018-10-13T07:37:28.92-0600 [RTR/3] OUT jdbcpoc.cfapps.io - [2018-10-13T13:37:23.345+0000] "GET /delay?d1=5&d2=5 HTTP/1.1" 200 0 17 "-" "Apache-HttpClient/4.5.3 (Java/1.8.0_152)" "10.10.66.112:56408" "10.10.149.182:61070" x_forwarded_for:"24.11.122.135, 10.10.66.112" x_forwarded_proto:"http" vcap_request_id:"69d31c90-bff1-433f-7476-a0a4ac002141" response_time:5.578600976 app_id:"94d62bb6-bcdd-4f80-b701-37b1cee68def" app_index:"0" x_b3_traceid:"a8a5814a39b8ea9e" x_b3_spanid:"a8a5814a39b8ea9e" x_b3_parentspanid:"-"
   2018-10-13T07:37:28.92-0600 [RTR/3] OUT 
   2018-10-13T07:37:28.92-0600 [APP/PROC/WEB/0] OUT 2018-10-13 13:37:28.924 ERROR 16 --- [ HystrixTimer-2] c.n.h.c.javanica.command.GenericCommand  : failed to process fallback: 'secondaryCall'. secondaryCall fallback is a hystrix command. exception: 'class java.util.concurrent.TimeoutException' occurred in fallback wasn't ignored.
   2018-10-13T07:37:28.92-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured FALLBACK_FAILURE
   2018-10-13T07:37:28.92-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured EXCEPTION_THROWN
   2018-10-13T07:37:28.92-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured TIMEOUT
   2018-10-13T07:37:28.92-0600 [APP/PROC/WEB/0] OUT LOGGER::InfinalCall..null
   2018-10-13T07:37:28.92-0600 [APP/PROC/WEB/0] OUT 2018-10-13 13:37:28.926 ERROR 16 --- [ HystrixTimer-3] c.n.h.c.javanica.command.GenericCommand  : failed to process fallback is the method: 'finalCall'. 
   2018-10-13T07:37:28.92-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured FALLBACK_FAILURE
   2018-10-13T07:37:28.92-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured EXCEPTION_THROWN
   2018-10-13T07:37:28.92-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured TIMEOUT
   2018-10-13T07:37:28.92-0600 [APP/PROC/WEB/0] ERR com.netflix.hystrix.exception.HystrixRuntimeException: primaryCall timed-out and fallback failed.
   2018-10-13T07:37:28.92-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$22.call(AbstractCommand.java:825)
   2018-10-13T07:37:28.92-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$22.call(AbstractCommand.java:804)
   2018-10-13T07:37:28.92-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:140)
   2018-10-13T07:37:28.92-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:28.92-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:28.92-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$DeprecatedOnFallbackHookApplication$1.onError(AbstractCommand.java:1472)
   2018-10-13T07:37:28.92-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$FallbackHookApplication$1.onError(AbstractCommand.java:1397)
   2018-10-13T07:37:28.92-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:28.92-0600 [APP/PROC/WEB/0] ERR 	at rx.observers.Subscribers$5.onError(Subscribers.java:230)
   2018-10-13T07:37:28.92-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:44)
   2018-10-13T07:37:28.92-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:28)
   2018-10-13T07:37:28.92-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:28.92-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
   2018-10-13T07:37:28.92-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
   2018-10-13T07:37:28.92-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:28.92-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   2018-10-13T07:37:28.92-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   2018-10-13T07:37:28.92-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   2018-10-13T07:37:28.92-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   2018-10-13T07:37:28.92-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   2018-10-13T07:37:28.92-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   2018-10-13T07:37:28.92-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:28.92-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   2018-10-13T07:37:28.92-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   2018-10-13T07:37:28.92-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:28.92-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   2018-10-13T07:37:28.92-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   2018-10-13T07:37:28.93-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   2018-10-13T07:37:28.93-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   2018-10-13T07:37:28.93-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:28.93-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   2018-10-13T07:37:28.93-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   2018-10-13T07:37:28.93-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   2018-10-13T07:37:28.93-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   2018-10-13T07:37:28.93-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:28.93-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:142)
   2018-10-13T07:37:28.93-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:28.93-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:28.93-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator$1$1.run(AbstractCommand.java:1154)
   2018-10-13T07:37:28.93-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable$1.call(HystrixContextRunnable.java:45)
   2018-10-13T07:37:28.93-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable$1.call(HystrixContextRunnable.java:41)
   2018-10-13T07:37:28.93-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable.run(HystrixContextRunnable.java:61)
   2018-10-13T07:37:28.93-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator$1.tick(AbstractCommand.java:1159)
   2018-10-13T07:37:28.93-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.util.HystrixTimer$1.run(HystrixTimer.java:99)
   2018-10-13T07:37:28.93-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
   2018-10-13T07:37:28.93-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
   2018-10-13T07:37:28.93-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
   2018-10-13T07:37:28.93-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
   2018-10-13T07:37:28.93-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   2018-10-13T07:37:28.93-0600 [APP/PROC/WEB/0] OUT LOGGER::InfinalCall..null
   2018-10-13T07:37:28.93-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   2018-10-13T07:37:28.93-0600 [APP/PROC/WEB/0] ERR 	at java.lang.Thread.run(Thread.java:748)
   2018-10-13T07:37:28.93-0600 [APP/PROC/WEB/0] OUT 2018-10-13 13:37:28.931 ERROR 16 --- [ HystrixTimer-2] c.n.h.c.javanica.command.GenericCommand  : failed to process fallback is the method: 'finalCall'. 
   2018-10-13T07:37:28.93-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured FALLBACK_FAILURE
   2018-10-13T07:37:28.93-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured EXCEPTION_THROWN
   2018-10-13T07:37:28.93-0600 [APP/PROC/WEB/0] OUT 2018-10-13 13:37:28.931 ERROR 16 --- [ HystrixTimer-4] c.n.h.c.javanica.command.GenericCommand  : failed to process fallback: 'secondaryCall'. secondaryCall fallback is a hystrix command. exception: 'class java.util.concurrent.TimeoutException' occurred in fallback wasn't ignored.
   2018-10-13T07:37:28.93-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured FALLBACK_FAILURE
   2018-10-13T07:37:28.93-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured EXCEPTION_THROWN
   2018-10-13T07:37:28.93-0600 [APP/PROC/WEB/0] ERR Caused by: java.util.concurrent.TimeoutException
   2018-10-13T07:37:28.93-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand.handleTimeoutViaFallback(AbstractCommand.java:997)
   2018-10-13T07:37:28.93-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand.access$500(AbstractCommand.java:60)
   2018-10-13T07:37:28.93-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$12.call(AbstractCommand.java:610)
   2018-10-13T07:37:28.93-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$12.call(AbstractCommand.java:601)
   2018-10-13T07:37:28.93-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:140)
   2018-10-13T07:37:28.93-0600 [APP/PROC/WEB/0] ERR 	... 15 more
   2018-10-13T07:37:28.93-0600 [APP/PROC/WEB/0] ERR com.netflix.hystrix.exception.HystrixRuntimeException: primaryCall timed-out and fallback failed.
   2018-10-13T07:37:28.93-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$22.call(AbstractCommand.java:825)
   2018-10-13T07:37:28.93-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$22.call(AbstractCommand.java:804)
   2018-10-13T07:37:28.93-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:140)
   2018-10-13T07:37:28.93-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:28.93-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:28.93-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$DeprecatedOnFallbackHookApplication$1.onError(AbstractCommand.java:1472)
   2018-10-13T07:37:28.93-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$FallbackHookApplication$1.onError(AbstractCommand.java:1397)
   2018-10-13T07:37:28.93-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:28.93-0600 [APP/PROC/WEB/0] ERR 	at rx.observers.Subscribers$5.onError(Subscribers.java:230)
   2018-10-13T07:37:28.93-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:44)
   2018-10-13T07:37:28.93-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:28)
   2018-10-13T07:37:28.93-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:28.93-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
   2018-10-13T07:37:28.93-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
   2018-10-13T07:37:28.93-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:28.93-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   2018-10-13T07:37:28.93-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   2018-10-13T07:37:28.93-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   2018-10-13T07:37:28.95-0600 [RTR/4] OUT jdbcpoc.cfapps.io - [2018-10-13T13:37:23.344+0000] "GET /delay?d1=5&d2=5 HTTP/1.1" 200 0 52 "-" "Apache-HttpClient/4.5.3 (Java/1.8.0_152)" "10.10.66.112:32864" "10.10.149.182:61070" x_forwarded_for:"24.11.122.135, 10.10.66.112" x_forwarded_proto:"http" vcap_request_id:"5d2e8911-0c6a-404e-56a9-e37b99c65d2f" response_time:5.609602862 app_id:"94d62bb6-bcdd-4f80-b701-37b1cee68def" app_index:"0" x_b3_traceid:"ff91715530ce4386" x_b3_spanid:"ff91715530ce4386" x_b3_parentspanid:"-"
   2018-10-13T07:37:28.95-0600 [RTR/4] OUT 
   2018-10-13T07:37:28.98-0600 [RTR/1] OUT jdbcpoc.cfapps.io - [2018-10-13T13:37:23.344+0000] "GET /delay?d1=5&d2=5 HTTP/1.1" 200 0 52 "-" "Apache-HttpClient/4.5.3 (Java/1.8.0_152)" "10.10.66.112:33556" "10.10.149.182:61070" x_forwarded_for:"24.11.122.135, 10.10.66.112" x_forwarded_proto:"http" vcap_request_id:"7dc95773-9b0b-49e8-4c16-7a2bacf6e424" response_time:5.639281537 app_id:"94d62bb6-bcdd-4f80-b701-37b1cee68def" app_index:"0" x_b3_traceid:"c1c53aabb5004e00" x_b3_spanid:"c1c53aabb5004e00" x_b3_parentspanid:"-"
   2018-10-13T07:37:28.98-0600 [RTR/1] OUT 
   2018-10-13T07:37:28.99-0600 [RTR/5] OUT jdbcpoc.cfapps.io - [2018-10-13T13:37:23.365+0000] "GET /delay?d1=5&d2=5 HTTP/1.1" 200 0 52 "-" "Apache-HttpClient/4.5.3 (Java/1.8.0_152)" "10.10.66.112:62266" "10.10.149.182:61070" x_forwarded_for:"24.11.122.135, 10.10.66.112" x_forwarded_proto:"http" vcap_request_id:"cd86b0f0-fad1-49dd-7652-64510edd9763" response_time:5.63105007 app_id:"94d62bb6-bcdd-4f80-b701-37b1cee68def" app_index:"0" x_b3_traceid:"972c61cae7c2ba34" x_b3_spanid:"972c61cae7c2ba34" x_b3_parentspanid:"-"
   2018-10-13T07:37:28.99-0600 [RTR/5] OUT 
   2018-10-13T07:37:28.93-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   2018-10-13T07:37:28.94-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   2018-10-13T07:37:28.94-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   2018-10-13T07:37:28.94-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:28.94-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   2018-10-13T07:37:28.94-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   2018-10-13T07:37:28.94-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:28.94-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   2018-10-13T07:37:28.94-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   2018-10-13T07:37:28.94-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   2018-10-13T07:37:28.94-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   2018-10-13T07:37:28.94-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:28.94-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   2018-10-13T07:37:28.94-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   2018-10-13T07:37:28.94-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   2018-10-13T07:37:28.94-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   2018-10-13T07:37:28.94-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:28.94-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:142)
   2018-10-13T07:37:28.94-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:28.94-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:28.94-0600 [APP/PROC/WEB/0] OUT LOGGER::In Secondary..null
   2018-10-13T07:37:28.94-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator$1$1.run(AbstractCommand.java:1154)
   2018-10-13T07:37:28.94-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable$1.call(HystrixContextRunnable.java:45)
   2018-10-13T07:37:28.94-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable$1.call(HystrixContextRunnable.java:41)
   2018-10-13T07:37:28.94-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable.run(HystrixContextRunnable.java:61)
   2018-10-13T07:37:28.94-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator$1.tick(AbstractCommand.java:1159)
   2018-10-13T07:37:28.94-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.util.HystrixTimer$1.run(HystrixTimer.java:99)
   2018-10-13T07:37:28.94-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
   2018-10-13T07:37:28.94-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
   2018-10-13T07:37:28.94-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
   2018-10-13T07:37:28.94-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
   2018-10-13T07:37:28.94-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   2018-10-13T07:37:28.94-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   2018-10-13T07:37:28.94-0600 [APP/PROC/WEB/0] ERR 	at java.lang.Thread.run(Thread.java:748)
   2018-10-13T07:37:28.95-0600 [APP/PROC/WEB/0] OUT 2018-10-13 13:37:28.935 ERROR 16 --- [ HystrixTimer-1] c.n.h.c.javanica.command.GenericCommand  : failed to process fallback: 'secondaryCall'. secondaryCall fallback is a hystrix command. exception: 'class java.util.concurrent.TimeoutException' occurred in fallback wasn't ignored.
   2018-10-13T07:37:28.95-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured FALLBACK_FAILURE
   2018-10-13T07:37:28.95-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured EXCEPTION_THROWN
   2018-10-13T07:37:28.97-0600 [APP/PROC/WEB/0] ERR Caused by: java.util.concurrent.TimeoutException
   2018-10-13T07:37:28.97-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand.handleTimeoutViaFallback(AbstractCommand.java:997)
   2018-10-13T07:37:28.97-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand.access$500(AbstractCommand.java:60)
   2018-10-13T07:37:28.97-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$12.call(AbstractCommand.java:610)
   2018-10-13T07:37:28.97-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$12.call(AbstractCommand.java:601)
   2018-10-13T07:37:28.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:140)
   2018-10-13T07:37:28.97-0600 [APP/PROC/WEB/0] ERR 	... 15 more
   2018-10-13T07:37:28.97-0600 [APP/PROC/WEB/0] ERR com.netflix.hystrix.exception.HystrixRuntimeException: primaryCall timed-out and fallback failed.
   2018-10-13T07:37:28.97-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$22.call(AbstractCommand.java:825)
   2018-10-13T07:37:28.97-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$22.call(AbstractCommand.java:804)
   2018-10-13T07:37:28.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:140)
   2018-10-13T07:37:28.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:28.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:28.97-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$DeprecatedOnFallbackHookApplication$1.onError(AbstractCommand.java:1472)
   2018-10-13T07:37:28.97-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$FallbackHookApplication$1.onError(AbstractCommand.java:1397)
   2018-10-13T07:37:28.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:28.97-0600 [APP/PROC/WEB/0] ERR 	at rx.observers.Subscribers$5.onError(Subscribers.java:230)
   2018-10-13T07:37:28.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:44)
   2018-10-13T07:37:28.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:28)
   2018-10-13T07:37:28.97-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:28.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
   2018-10-13T07:37:28.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
   2018-10-13T07:37:28.97-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:28.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   2018-10-13T07:37:28.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   2018-10-13T07:37:28.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   2018-10-13T07:37:28.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   2018-10-13T07:37:28.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   2018-10-13T07:37:28.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   2018-10-13T07:37:28.97-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:28.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   2018-10-13T07:37:28.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   2018-10-13T07:37:28.97-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:28.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   2018-10-13T07:37:28.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   2018-10-13T07:37:28.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   2018-10-13T07:37:28.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   2018-10-13T07:37:28.97-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:28.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   2018-10-13T07:37:28.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   2018-10-13T07:37:28.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   2018-10-13T07:37:28.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   2018-10-13T07:37:28.97-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:28.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:142)
   2018-10-13T07:37:28.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:28.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:28.97-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator$1$1.run(AbstractCommand.java:1154)
   2018-10-13T07:37:28.97-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable$1.call(HystrixContextRunnable.java:45)
   2018-10-13T07:37:28.97-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable$1.call(HystrixContextRunnable.java:41)
   2018-10-13T07:37:28.97-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable.run(HystrixContextRunnable.java:61)
   2018-10-13T07:37:28.97-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator$1.tick(AbstractCommand.java:1159)
   2018-10-13T07:37:28.97-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.util.HystrixTimer$1.run(HystrixTimer.java:99)
   2018-10-13T07:37:28.97-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
   2018-10-13T07:37:28.97-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
   2018-10-13T07:37:28.97-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
   2018-10-13T07:37:28.97-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
   2018-10-13T07:37:28.97-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   2018-10-13T07:37:28.97-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   2018-10-13T07:37:28.97-0600 [APP/PROC/WEB/0] ERR 	at java.lang.Thread.run(Thread.java:748)
   2018-10-13T07:37:28.98-0600 [APP/PROC/WEB/0] ERR Caused by: java.util.concurrent.TimeoutException
   2018-10-13T07:37:28.98-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand.handleTimeoutViaFallback(AbstractCommand.java:997)
   2018-10-13T07:37:28.99-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand.access$500(AbstractCommand.java:60)
   2018-10-13T07:37:28.99-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$12.call(AbstractCommand.java:610)
   2018-10-13T07:37:28.99-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$12.call(AbstractCommand.java:601)
   2018-10-13T07:37:28.99-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:140)
   2018-10-13T07:37:28.99-0600 [APP/PROC/WEB/0] ERR 	... 15 more
   2018-10-13T07:37:29.13-0600 [APP/PROC/WEB/0] OUT LOGGER::In Primary..
   2018-10-13T07:37:29.46-0600 [RTR/6] OUT jdbcpoc.cfapps.io - [2018-10-13T13:37:23.951+0000] "GET /delay?d1=5&d2=5 HTTP/1.1" 200 0 52 "-" "Apache-HttpClient/4.5.3 (Java/1.8.0_152)" "10.10.66.112:6642" "10.10.149.182:61070" x_forwarded_for:"24.11.122.135, 10.10.66.112" x_forwarded_proto:"http" vcap_request_id:"0535d707-7abc-410a-445e-62a41ad01513" response_time:5.511445922 app_id:"94d62bb6-bcdd-4f80-b701-37b1cee68def" app_index:"0" x_b3_traceid:"c4db8f2241700413" x_b3_spanid:"c4db8f2241700413" x_b3_parentspanid:"-"
   2018-10-13T07:37:29.46-0600 [RTR/6] OUT 
   2018-10-13T07:37:29.43-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured TIMEOUT
   2018-10-13T07:37:29.43-0600 [APP/PROC/WEB/0] OUT LOGGER::InfinalCall..null
   2018-10-13T07:37:29.43-0600 [APP/PROC/WEB/0] OUT 2018-10-13 13:37:29.438 ERROR 16 --- [ HystrixTimer-2] c.n.h.c.javanica.command.GenericCommand  : failed to process fallback is the method: 'finalCall'. 
   2018-10-13T07:37:29.43-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured FALLBACK_FAILURE
   2018-10-13T07:37:29.43-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured EXCEPTION_THROWN
   2018-10-13T07:37:29.44-0600 [APP/PROC/WEB/0] OUT 2018-10-13 13:37:29.441 ERROR 16 --- [ HystrixTimer-3] c.n.h.c.javanica.command.GenericCommand  : failed to process fallback: 'secondaryCall'. secondaryCall fallback is a hystrix command. exception: 'class java.util.concurrent.TimeoutException' occurred in fallback wasn't ignored.
   2018-10-13T07:37:29.44-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured FALLBACK_FAILURE
   2018-10-13T07:37:29.45-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured EXCEPTION_THROWN
   2018-10-13T07:37:29.45-0600 [APP/PROC/WEB/0] ERR com.netflix.hystrix.exception.HystrixRuntimeException: primaryCall timed-out and fallback failed.
   2018-10-13T07:37:29.45-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$22.call(AbstractCommand.java:825)
   2018-10-13T07:37:29.45-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$22.call(AbstractCommand.java:804)
   2018-10-13T07:37:29.45-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:140)
   2018-10-13T07:37:29.45-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:29.45-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:29.45-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$DeprecatedOnFallbackHookApplication$1.onError(AbstractCommand.java:1472)
   2018-10-13T07:37:29.45-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$FallbackHookApplication$1.onError(AbstractCommand.java:1397)
   2018-10-13T07:37:29.45-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:29.45-0600 [APP/PROC/WEB/0] ERR 	at rx.observers.Subscribers$5.onError(Subscribers.java:230)
   2018-10-13T07:37:29.45-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:44)
   2018-10-13T07:37:29.45-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:28)
   2018-10-13T07:37:29.45-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:29.45-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
   2018-10-13T07:37:29.45-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
   2018-10-13T07:37:29.45-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:29.45-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   2018-10-13T07:37:29.45-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   2018-10-13T07:37:29.45-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   2018-10-13T07:37:29.45-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   2018-10-13T07:37:29.45-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   2018-10-13T07:37:29.45-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   2018-10-13T07:37:29.45-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:29.45-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   2018-10-13T07:37:29.45-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   2018-10-13T07:37:29.45-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:29.45-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   2018-10-13T07:37:29.45-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   2018-10-13T07:37:29.45-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   2018-10-13T07:37:29.45-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   2018-10-13T07:37:29.45-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:29.45-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   2018-10-13T07:37:29.45-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   2018-10-13T07:37:29.45-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   2018-10-13T07:37:29.45-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   2018-10-13T07:37:29.45-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:29.45-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:142)
   2018-10-13T07:37:29.45-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:29.45-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:29.45-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator$1$1.run(AbstractCommand.java:1154)
   2018-10-13T07:37:29.45-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable$1.call(HystrixContextRunnable.java:45)
   2018-10-13T07:37:29.45-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable$1.call(HystrixContextRunnable.java:41)
   2018-10-13T07:37:29.45-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable.run(HystrixContextRunnable.java:61)
   2018-10-13T07:37:29.45-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator$1.tick(AbstractCommand.java:1159)
   2018-10-13T07:37:29.46-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.util.HystrixTimer$1.run(HystrixTimer.java:99)
   2018-10-13T07:37:29.46-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
   2018-10-13T07:37:29.46-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
   2018-10-13T07:37:29.46-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
   2018-10-13T07:37:29.46-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
   2018-10-13T07:37:29.46-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   2018-10-13T07:37:29.46-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   2018-10-13T07:37:29.46-0600 [APP/PROC/WEB/0] ERR 	at java.lang.Thread.run(Thread.java:748)
   2018-10-13T07:37:29.46-0600 [APP/PROC/WEB/0] ERR Caused by: java.util.concurrent.TimeoutException
   2018-10-13T07:37:29.46-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand.handleTimeoutViaFallback(AbstractCommand.java:997)
   2018-10-13T07:37:29.46-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand.access$500(AbstractCommand.java:60)
   2018-10-13T07:37:29.46-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$12.call(AbstractCommand.java:610)
   2018-10-13T07:37:29.46-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$12.call(AbstractCommand.java:601)
   2018-10-13T07:37:29.46-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:140)
   2018-10-13T07:37:29.46-0600 [APP/PROC/WEB/0] ERR 	... 15 more
   2018-10-13T07:37:29.64-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured TIMEOUT
   2018-10-13T07:37:29.64-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured TIMEOUT
   2018-10-13T07:37:29.64-0600 [APP/PROC/WEB/0] OUT LOGGER::In Primary..
   2018-10-13T07:37:29.64-0600 [APP/PROC/WEB/0] OUT LOGGER::In Secondary..null
   2018-10-13T07:37:29.64-0600 [APP/PROC/WEB/0] OUT LOGGER::In Secondary..null
   2018-10-13T07:37:29.65-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured TIMEOUT
   2018-10-13T07:37:29.65-0600 [APP/PROC/WEB/0] OUT LOGGER::In Secondary..null
   2018-10-13T07:37:29.66-0600 [APP/PROC/WEB/0] OUT LOGGER::In Primary..
   2018-10-13T07:37:29.68-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured TIMEOUT
   2018-10-13T07:37:29.68-0600 [APP/PROC/WEB/0] OUT LOGGER::In Primary..
   2018-10-13T07:37:29.68-0600 [APP/PROC/WEB/0] OUT LOGGER::In Secondary..null
   2018-10-13T07:37:38.17-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured SUCCESS
   2018-10-13T07:37:38.17-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured FALLBACK_SUCCESS
   2018-10-13T07:37:38.17-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured TIMEOUT
   2018-10-13T07:37:38.17-0600 [RTR/1] OUT jdbcpoc.cfapps.io - [2018-10-13T13:37:29.114+0000] "GET /delay?d1=5&d2=5 HTTP/1.1" 200 0 17 "-" "Apache-HttpClient/4.5.3 (Java/1.8.0_152)" "10.10.66.112:33556" "10.10.149.182:61070" x_forwarded_for:"24.11.122.135, 10.10.66.112" x_forwarded_proto:"http" vcap_request_id:"68012537-4ff3-48de-5759-f679ad198ef0" response_time:9.063994291 app_id:"94d62bb6-bcdd-4f80-b701-37b1cee68def" app_index:"0" x_b3_traceid:"d58401159c001426" x_b3_spanid:"d58401159c001426" x_b3_parentspanid:"-"
   2018-10-13T07:37:38.17-0600 [RTR/1] OUT 
   2018-10-13T07:37:38.18-0600 [APP/PROC/WEB/0] OUT LOGGER::InfinalCall..null
   2018-10-13T07:37:38.18-0600 [APP/PROC/WEB/0] OUT 2018-10-13 13:37:38.183 ERROR 16 --- [ HystrixTimer-4] c.n.h.c.javanica.command.GenericCommand  : failed to process fallback is the method: 'finalCall'. 
   2018-10-13T07:37:38.18-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured FALLBACK_FAILURE
   2018-10-13T07:37:38.18-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured EXCEPTION_THROWN
   2018-10-13T07:37:38.18-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured TIMEOUT
   2018-10-13T07:37:38.18-0600 [APP/PROC/WEB/0] OUT 2018-10-13 13:37:38.185 ERROR 16 --- [ HystrixTimer-1] c.n.h.c.javanica.command.GenericCommand  : failed to process fallback: 'secondaryCall'. secondaryCall fallback is a hystrix command. exception: 'class java.util.concurrent.TimeoutException' occurred in fallback wasn't ignored.
   2018-10-13T07:37:38.18-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured FALLBACK_FAILURE
   2018-10-13T07:37:38.18-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured EXCEPTION_THROWN
   2018-10-13T07:37:38.18-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured TIMEOUT
   2018-10-13T07:37:38.18-0600 [APP/PROC/WEB/0] OUT LOGGER::In Secondary..null
   2018-10-13T07:37:38.19-0600 [APP/PROC/WEB/0] ERR com.netflix.hystrix.exception.HystrixRuntimeException: primaryCall timed-out and fallback failed.
   2018-10-13T07:37:38.19-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$22.call(AbstractCommand.java:825)
   2018-10-13T07:37:38.19-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$22.call(AbstractCommand.java:804)
   2018-10-13T07:37:38.19-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:140)
   2018-10-13T07:37:38.19-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:38.19-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:38.19-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$DeprecatedOnFallbackHookApplication$1.onError(AbstractCommand.java:1472)
   2018-10-13T07:37:38.19-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$FallbackHookApplication$1.onError(AbstractCommand.java:1397)
   2018-10-13T07:37:38.19-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:38.20-0600 [APP/PROC/WEB/0] ERR 	at rx.observers.Subscribers$5.onError(Subscribers.java:230)
   2018-10-13T07:37:38.20-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:44)
   2018-10-13T07:37:38.20-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:28)
   2018-10-13T07:37:38.20-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:38.20-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
   2018-10-13T07:37:38.20-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
   2018-10-13T07:37:38.20-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:38.20-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   2018-10-13T07:37:38.20-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   2018-10-13T07:37:38.20-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   2018-10-13T07:37:38.20-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   2018-10-13T07:37:38.20-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   2018-10-13T07:37:38.20-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   2018-10-13T07:37:38.20-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:38.20-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   2018-10-13T07:37:38.20-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   2018-10-13T07:37:38.20-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:38.20-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   2018-10-13T07:37:38.20-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   2018-10-13T07:37:38.20-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   2018-10-13T07:37:38.20-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   2018-10-13T07:37:38.20-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:38.20-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   2018-10-13T07:37:38.20-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   2018-10-13T07:37:38.20-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   2018-10-13T07:37:38.20-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   2018-10-13T07:37:38.20-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:38.20-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:142)
   2018-10-13T07:37:38.20-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:38.20-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:38.21-0600 [RTR/6] OUT jdbcpoc.cfapps.io - [2018-10-13T13:37:29.125+0000] "GET /delay?d1=5&d2=5 HTTP/1.1" 200 0 52 "-" "Apache-HttpClient/4.5.3 (Java/1.8.0_152)" "10.10.66.112:7276" "10.10.149.182:61070" x_forwarded_for:"24.11.122.135, 10.10.66.112" x_forwarded_proto:"http" vcap_request_id:"ab98a321-f041-4e46-61ca-f77344c61b78" response_time:9.092110492 app_id:"94d62bb6-bcdd-4f80-b701-37b1cee68def" app_index:"0" x_b3_traceid:"060b013f033900e7" x_b3_spanid:"060b013f033900e7" x_b3_parentspanid:"-"
   2018-10-13T07:37:38.21-0600 [RTR/6] OUT 
   2018-10-13T07:37:38.24-0600 [RTR/9] OUT jdbcpoc.cfapps.io - [2018-10-13T13:37:29.152+0000] "GET /delay?d1=5&d2=5 HTTP/1.1" 200 0 52 "-" "Apache-HttpClient/4.5.3 (Java/1.8.0_152)" "10.10.66.112:17216" "10.10.149.182:61070" x_forwarded_for:"24.11.122.135, 10.10.66.112" x_forwarded_proto:"http" vcap_request_id:"7c88b3a5-eaeb-48d1-596f-0939f81faaef" response_time:9.091930916 app_id:"94d62bb6-bcdd-4f80-b701-37b1cee68def" app_index:"0" x_b3_traceid:"fe3cd60a78c917b2" x_b3_spanid:"fe3cd60a78c917b2" x_b3_parentspanid:"-"
   2018-10-13T07:37:38.24-0600 [RTR/9] OUT 
   2018-10-13T07:37:38.24-0600 [RTR/10] OUT jdbcpoc.cfapps.io - [2018-10-13T13:37:29.168+0000] "GET /delay?d1=5&d2=5 HTTP/1.1" 200 0 52 "-" "Apache-HttpClient/4.5.3 (Java/1.8.0_152)" "10.10.66.112:4474" "10.10.149.182:61070" x_forwarded_for:"24.11.122.135, 10.10.66.112" x_forwarded_proto:"http" vcap_request_id:"1265fc5a-24bc-4540-607e-5c29abb071a0" response_time:9.07671608 app_id:"94d62bb6-bcdd-4f80-b701-37b1cee68def" app_index:"0" x_b3_traceid:"580e9889c495a543" x_b3_spanid:"580e9889c495a543" x_b3_parentspanid:"-"
   2018-10-13T07:37:38.24-0600 [RTR/10] OUT 
   2018-10-13T07:37:38.20-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator$1$1.run(AbstractCommand.java:1154)
   2018-10-13T07:37:38.20-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable$1.call(HystrixContextRunnable.java:45)
   2018-10-13T07:37:38.20-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable$1.call(HystrixContextRunnable.java:41)
   2018-10-13T07:37:38.20-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable.run(HystrixContextRunnable.java:61)
   2018-10-13T07:37:38.20-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator$1.tick(AbstractCommand.java:1159)
   2018-10-13T07:37:38.20-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.util.HystrixTimer$1.run(HystrixTimer.java:99)
   2018-10-13T07:37:38.20-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
   2018-10-13T07:37:38.20-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
   2018-10-13T07:37:38.20-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
   2018-10-13T07:37:38.20-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
   2018-10-13T07:37:38.20-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   2018-10-13T07:37:38.20-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   2018-10-13T07:37:38.20-0600 [APP/PROC/WEB/0] ERR 	at java.lang.Thread.run(Thread.java:748)
   2018-10-13T07:37:38.21-0600 [APP/PROC/WEB/0] ERR Caused by: java.util.concurrent.TimeoutException
   2018-10-13T07:37:38.21-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand.handleTimeoutViaFallback(AbstractCommand.java:997)
   2018-10-13T07:37:38.21-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand.access$500(AbstractCommand.java:60)
   2018-10-13T07:37:38.21-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$12.call(AbstractCommand.java:610)
   2018-10-13T07:37:38.21-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$12.call(AbstractCommand.java:601)
   2018-10-13T07:37:38.21-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:140)
   2018-10-13T07:37:38.21-0600 [APP/PROC/WEB/0] ERR 	... 15 more
   2018-10-13T07:37:38.21-0600 [APP/PROC/WEB/0] OUT LOGGER::InfinalCall..null
   2018-10-13T07:37:38.21-0600 [APP/PROC/WEB/0] OUT 2018-10-13 13:37:38.218 ERROR 16 --- [ HystrixTimer-1] c.n.h.c.javanica.command.GenericCommand  : failed to process fallback is the method: 'finalCall'. 
   2018-10-13T07:37:38.21-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured FALLBACK_FAILURE
   2018-10-13T07:37:38.21-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured EXCEPTION_THROWN
   2018-10-13T07:37:38.21-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured TIMEOUT
   2018-10-13T07:37:38.22-0600 [APP/PROC/WEB/0] OUT 2018-10-13 13:37:38.225 ERROR 16 --- [ HystrixTimer-2] c.n.h.c.javanica.command.GenericCommand  : failed to process fallback: 'secondaryCall'. secondaryCall fallback is a hystrix command. exception: 'class java.util.concurrent.TimeoutException' occurred in fallback wasn't ignored.
   2018-10-13T07:37:38.22-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured FALLBACK_FAILURE
   2018-10-13T07:37:38.22-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured EXCEPTION_THROWN
   2018-10-13T07:37:38.22-0600 [APP/PROC/WEB/0] OUT LOGGER::InfinalCall..null
   2018-10-13T07:37:38.22-0600 [APP/PROC/WEB/0] OUT 2018-10-13 13:37:38.226 ERROR 16 --- [ HystrixTimer-1] c.n.h.c.javanica.command.GenericCommand  : failed to process fallback is the method: 'finalCall'. 
   2018-10-13T07:37:38.22-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured FALLBACK_FAILURE
   2018-10-13T07:37:38.22-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured EXCEPTION_THROWN
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] ERR com.netflix.hystrix.exception.HystrixRuntimeException: primaryCall timed-out and fallback failed.
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$22.call(AbstractCommand.java:825)
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] OUT 2018-10-13 13:37:38.230 ERROR 16 --- [ HystrixTimer-3] c.n.h.c.javanica.command.GenericCommand  : failed to process fallback: 'secondaryCall'. secondaryCall fallback is a hystrix command. exception: 'class java.util.concurrent.TimeoutException' occurred in fallback wasn't ignored.
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$22.call(AbstractCommand.java:804)
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured FALLBACK_FAILURE
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:140)
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured EXCEPTION_THROWN
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$DeprecatedOnFallbackHookApplication$1.onError(AbstractCommand.java:1472)
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$FallbackHookApplication$1.onError(AbstractCommand.java:1397)
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] ERR 	at rx.observers.Subscribers$5.onError(Subscribers.java:230)
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:44)
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:28)
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:142)
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator$1$1.run(AbstractCommand.java:1154)
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable$1.call(HystrixContextRunnable.java:45)
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable$1.call(HystrixContextRunnable.java:41)
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable.run(HystrixContextRunnable.java:61)
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator$1.tick(AbstractCommand.java:1159)
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.util.HystrixTimer$1.run(HystrixTimer.java:99)
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] ERR 	at java.lang.Thread.run(Thread.java:748)
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] ERR Caused by: java.util.concurrent.TimeoutException
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand.handleTimeoutViaFallback(AbstractCommand.java:997)
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand.access$500(AbstractCommand.java:60)
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$12.call(AbstractCommand.java:610)
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$12.call(AbstractCommand.java:601)
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:140)
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] ERR 	... 15 more
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] ERR com.netflix.hystrix.exception.HystrixRuntimeException: primaryCall timed-out and fallback failed.
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$22.call(AbstractCommand.java:825)
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$22.call(AbstractCommand.java:804)
   2018-10-13T07:37:38.23-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:140)
   2018-10-13T07:37:38.24-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:38.24-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:38.24-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$DeprecatedOnFallbackHookApplication$1.onError(AbstractCommand.java:1472)
   2018-10-13T07:37:38.24-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$FallbackHookApplication$1.onError(AbstractCommand.java:1397)
   2018-10-13T07:37:38.24-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:38.24-0600 [APP/PROC/WEB/0] ERR 	at rx.observers.Subscribers$5.onError(Subscribers.java:230)
   2018-10-13T07:37:38.24-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:44)
   2018-10-13T07:37:38.24-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:28)
   2018-10-13T07:37:38.24-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:38.24-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
   2018-10-13T07:37:38.24-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
   2018-10-13T07:37:38.24-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:38.24-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   2018-10-13T07:37:38.24-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   2018-10-13T07:37:38.24-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   2018-10-13T07:37:38.24-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   2018-10-13T07:37:38.24-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   2018-10-13T07:37:38.24-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   2018-10-13T07:37:38.24-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:38.24-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   2018-10-13T07:37:38.24-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   2018-10-13T07:37:38.24-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:38.24-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   2018-10-13T07:37:38.24-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   2018-10-13T07:37:38.24-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   2018-10-13T07:37:38.24-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   2018-10-13T07:37:38.24-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:38.24-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   2018-10-13T07:37:38.24-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   2018-10-13T07:37:38.24-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   2018-10-13T07:37:38.24-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   2018-10-13T07:37:38.24-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:38.24-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:142)
   2018-10-13T07:37:38.24-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:38.24-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:38.24-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator$1$1.run(AbstractCommand.java:1154)
   2018-10-13T07:37:38.24-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable$1.call(HystrixContextRunnable.java:45)
   2018-10-13T07:37:38.24-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable$1.call(HystrixContextRunnable.java:41)
   2018-10-13T07:37:38.24-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable.run(HystrixContextRunnable.java:61)
   2018-10-13T07:37:38.24-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator$1.tick(AbstractCommand.java:1159)
   2018-10-13T07:37:38.24-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.util.HystrixTimer$1.run(HystrixTimer.java:99)
   2018-10-13T07:37:38.24-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
   2018-10-13T07:37:38.24-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
   2018-10-13T07:37:38.24-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
   2018-10-13T07:37:38.24-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
   2018-10-13T07:37:38.24-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   2018-10-13T07:37:38.24-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   2018-10-13T07:37:38.24-0600 [APP/PROC/WEB/0] ERR 	at java.lang.Thread.run(Thread.java:748)
   2018-10-13T07:37:38.24-0600 [APP/PROC/WEB/0] ERR Caused by: java.util.concurrent.TimeoutException
   2018-10-13T07:37:38.24-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand.handleTimeoutViaFallback(AbstractCommand.java:997)
   2018-10-13T07:37:38.24-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand.access$500(AbstractCommand.java:60)
   2018-10-13T07:37:38.24-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$12.call(AbstractCommand.java:610)
   2018-10-13T07:37:38.24-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$12.call(AbstractCommand.java:601)
   2018-10-13T07:37:38.24-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:140)
   2018-10-13T07:37:38.24-0600 [APP/PROC/WEB/0] ERR 	... 15 more
   2018-10-13T07:37:38.42-0600 [APP/PROC/WEB/0] OUT LOGGER::In Primary..
   2018-10-13T07:37:38.70-0600 [RTR/8] OUT jdbcpoc.cfapps.io - [2018-10-13T13:37:29.631+0000] "GET /delay?d1=5&d2=5 HTTP/1.1" 200 0 52 "-" "Apache-HttpClient/4.5.3 (Java/1.8.0_152)" "10.10.66.112:44768" "10.10.149.182:61070" x_forwarded_for:"24.11.122.135, 10.10.66.112" x_forwarded_proto:"http" vcap_request_id:"ba24e774-e280-4322-5d38-fd98464efb1d" response_time:9.071529501 app_id:"94d62bb6-bcdd-4f80-b701-37b1cee68def" app_index:"0" x_b3_traceid:"e6d3c3e6012f865b" x_b3_spanid:"e6d3c3e6012f865b" x_b3_parentspanid:"-"
   2018-10-13T07:37:38.70-0600 [RTR/8] OUT 
   2018-10-13T07:37:38.68-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured TIMEOUT
   2018-10-13T07:37:38.69-0600 [APP/PROC/WEB/0] OUT LOGGER::InfinalCall..null
   2018-10-13T07:37:38.69-0600 [APP/PROC/WEB/0] OUT 2018-10-13 13:37:38.691 ERROR 16 --- [ HystrixTimer-2] c.n.h.c.javanica.command.GenericCommand  : failed to process fallback is the method: 'finalCall'. 
   2018-10-13T07:37:38.69-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured FALLBACK_FAILURE
   2018-10-13T07:37:38.69-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured EXCEPTION_THROWN
   2018-10-13T07:37:38.69-0600 [APP/PROC/WEB/0] OUT 2018-10-13 13:37:38.692 ERROR 16 --- [ HystrixTimer-4] c.n.h.c.javanica.command.GenericCommand  : failed to process fallback: 'secondaryCall'. secondaryCall fallback is a hystrix command. exception: 'class java.util.concurrent.TimeoutException' occurred in fallback wasn't ignored.
   2018-10-13T07:37:38.69-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured FALLBACK_FAILURE
   2018-10-13T07:37:38.69-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured EXCEPTION_THROWN
   2018-10-13T07:37:38.69-0600 [APP/PROC/WEB/0] ERR com.netflix.hystrix.exception.HystrixRuntimeException: primaryCall timed-out and fallback failed.
   2018-10-13T07:37:38.69-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$22.call(AbstractCommand.java:825)
   2018-10-13T07:37:38.69-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$22.call(AbstractCommand.java:804)
   2018-10-13T07:37:38.69-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:140)
   2018-10-13T07:37:38.69-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:38.69-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:38.69-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$DeprecatedOnFallbackHookApplication$1.onError(AbstractCommand.java:1472)
   2018-10-13T07:37:38.69-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$FallbackHookApplication$1.onError(AbstractCommand.java:1397)
   2018-10-13T07:37:38.69-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:38.69-0600 [APP/PROC/WEB/0] ERR 	at rx.observers.Subscribers$5.onError(Subscribers.java:230)
   2018-10-13T07:37:38.69-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:44)
   2018-10-13T07:37:38.69-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:28)
   2018-10-13T07:37:38.69-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:38.69-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
   2018-10-13T07:37:38.69-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
   2018-10-13T07:37:38.69-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:38.69-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   2018-10-13T07:37:38.69-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   2018-10-13T07:37:38.69-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   2018-10-13T07:37:38.69-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   2018-10-13T07:37:38.69-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   2018-10-13T07:37:38.69-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   2018-10-13T07:37:38.69-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:38.69-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   2018-10-13T07:37:38.69-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   2018-10-13T07:37:38.69-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:38.69-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   2018-10-13T07:37:38.69-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   2018-10-13T07:37:38.69-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   2018-10-13T07:37:38.69-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   2018-10-13T07:37:38.69-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:38.69-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   2018-10-13T07:37:38.69-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   2018-10-13T07:37:38.69-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   2018-10-13T07:37:38.70-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   2018-10-13T07:37:38.70-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:38.70-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:142)
   2018-10-13T07:37:38.70-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:38.70-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:38.70-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator$1$1.run(AbstractCommand.java:1154)
   2018-10-13T07:37:38.70-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable$1.call(HystrixContextRunnable.java:45)
   2018-10-13T07:37:38.70-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable$1.call(HystrixContextRunnable.java:41)
   2018-10-13T07:37:38.70-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable.run(HystrixContextRunnable.java:61)
   2018-10-13T07:37:38.70-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator$1.tick(AbstractCommand.java:1159)
   2018-10-13T07:37:38.70-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.util.HystrixTimer$1.run(HystrixTimer.java:99)
   2018-10-13T07:37:38.70-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
   2018-10-13T07:37:38.70-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
   2018-10-13T07:37:38.70-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
   2018-10-13T07:37:38.70-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
   2018-10-13T07:37:38.70-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   2018-10-13T07:37:38.70-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   2018-10-13T07:37:38.70-0600 [APP/PROC/WEB/0] ERR 	at java.lang.Thread.run(Thread.java:748)
   2018-10-13T07:37:38.70-0600 [APP/PROC/WEB/0] ERR Caused by: java.util.concurrent.TimeoutException
   2018-10-13T07:37:38.70-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand.handleTimeoutViaFallback(AbstractCommand.java:997)
   2018-10-13T07:37:38.70-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand.access$500(AbstractCommand.java:60)
   2018-10-13T07:37:38.70-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$12.call(AbstractCommand.java:610)
   2018-10-13T07:37:38.70-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$12.call(AbstractCommand.java:601)
   2018-10-13T07:37:38.70-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:140)
   2018-10-13T07:37:38.70-0600 [APP/PROC/WEB/0] ERR 	... 15 more
   2018-10-13T07:37:38.92-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured TIMEOUT
   2018-10-13T07:37:38.92-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured TIMEOUT
   2018-10-13T07:37:38.92-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured TIMEOUT
   2018-10-13T07:37:38.92-0600 [APP/PROC/WEB/0] OUT LOGGER::In Secondary..null
   2018-10-13T07:37:38.93-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured TIMEOUT
   2018-10-13T07:37:38.93-0600 [APP/PROC/WEB/0] OUT LOGGER::In Secondary..null
   2018-10-13T07:37:38.93-0600 [APP/PROC/WEB/0] OUT LOGGER::In Secondary..null
   2018-10-13T07:37:38.93-0600 [APP/PROC/WEB/0] OUT LOGGER::In Secondary..null
   2018-10-13T07:37:43.95-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured SUCCESS
   2018-10-13T07:37:43.95-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured FALLBACK_SUCCESS
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured TIMEOUT
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] OUT LOGGER::InfinalCall..null
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] OUT 2018-10-13 13:37:43.958 ERROR 16 --- [ HystrixTimer-1] c.n.h.c.javanica.command.GenericCommand  : failed to process fallback is the method: 'finalCall'. 
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured FALLBACK_FAILURE
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured EXCEPTION_THROWN
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured TIMEOUT
   2018-10-13T07:37:43.96-0600 [RTR/9] OUT jdbcpoc.cfapps.io - [2018-10-13T13:37:38.420+0000] "GET /delay?d1=5&d2=5 HTTP/1.1" 200 0 17 "-" "Apache-HttpClient/4.5.3 (Java/1.8.0_152)" "10.10.66.112:17272" "10.10.149.182:61070" x_forwarded_for:"24.11.122.135, 10.10.66.112" x_forwarded_proto:"http" vcap_request_id:"088c1de5-e3ef-4d6f-5685-55f23eb2b356" response_time:5.541480335 app_id:"94d62bb6-bcdd-4f80-b701-37b1cee68def" app_index:"0" x_b3_traceid:"df925b6b9932d849" x_b3_spanid:"df925b6b9932d849" x_b3_parentspanid:"-"
   2018-10-13T07:37:43.96-0600 [RTR/9] OUT 
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] OUT 2018-10-13 13:37:43.961 ERROR 16 --- [ HystrixTimer-3] c.n.h.c.javanica.command.GenericCommand  : failed to process fallback: 'secondaryCall'. secondaryCall fallback is a hystrix command. exception: 'class java.util.concurrent.TimeoutException' occurred in fallback wasn't ignored.
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured FALLBACK_FAILURE
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured EXCEPTION_THROWN
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured TIMEOUT
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] OUT LOGGER::InfinalCall..null
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] OUT 2018-10-13 13:37:43.963 ERROR 16 --- [ HystrixTimer-1] c.n.h.c.javanica.command.GenericCommand  : failed to process fallback is the method: 'finalCall'. 
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured FALLBACK_FAILURE
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured EXCEPTION_THROWN
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] OUT LOGGER::InfinalCall..null
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] OUT 2018-10-13 13:37:43.966 ERROR 16 --- [ HystrixTimer-3] c.n.h.c.javanica.command.GenericCommand  : failed to process fallback is the method: 'finalCall'. 
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured FALLBACK_FAILURE
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured EXCEPTION_THROWN
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] OUT 2018-10-13 13:37:43.966 ERROR 16 --- [ HystrixTimer-2] c.n.h.c.javanica.command.GenericCommand  : failed to process fallback: 'secondaryCall'. secondaryCall fallback is a hystrix command. exception: 'class java.util.concurrent.TimeoutException' occurred in fallback wasn't ignored.
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured FALLBACK_FAILURE
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured EXCEPTION_THROWN
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] ERR com.netflix.hystrix.exception.HystrixRuntimeException: primaryCall timed-out and fallback failed.
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$22.call(AbstractCommand.java:825)
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$22.call(AbstractCommand.java:804)
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:140)
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$DeprecatedOnFallbackHookApplication$1.onError(AbstractCommand.java:1472)
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$FallbackHookApplication$1.onError(AbstractCommand.java:1397)
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] ERR 	at rx.observers.Subscribers$5.onError(Subscribers.java:230)
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:44)
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:28)
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:142)
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator$1$1.run(AbstractCommand.java:1154)
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable$1.call(HystrixContextRunnable.java:45)
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable$1.call(HystrixContextRunnable.java:41)
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable.run(HystrixContextRunnable.java:61)
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator$1.tick(AbstractCommand.java:1159)
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.util.HystrixTimer$1.run(HystrixTimer.java:99)
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] ERR 	at java.lang.Thread.run(Thread.java:748)
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] OUT 2018-10-13 13:37:43.969 ERROR 16 --- [ HystrixTimer-4] c.n.h.c.javanica.command.GenericCommand  : failed to process fallback: 'secondaryCall'. secondaryCall fallback is a hystrix command. exception: 'class java.util.concurrent.TimeoutException' occurred in fallback wasn't ignored.
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured FALLBACK_FAILURE
   2018-10-13T07:37:43.96-0600 [APP/PROC/WEB/0] OUT **WARNING** Hystrix Event Occured EXCEPTION_THROWN
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR Caused by: java.util.concurrent.TimeoutException
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand.handleTimeoutViaFallback(AbstractCommand.java:997)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand.access$500(AbstractCommand.java:60)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$12.call(AbstractCommand.java:610)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$12.call(AbstractCommand.java:601)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:140)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	... 15 more
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR com.netflix.hystrix.exception.HystrixRuntimeException: primaryCall timed-out and fallback failed.
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$22.call(AbstractCommand.java:825)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$22.call(AbstractCommand.java:804)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:140)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$DeprecatedOnFallbackHookApplication$1.onError(AbstractCommand.java:1472)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$FallbackHookApplication$1.onError(AbstractCommand.java:1397)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at rx.observers.Subscribers$5.onError(Subscribers.java:230)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:44)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:28)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
   2018-10-13T07:37:43.97-0600 [RTR/1] OUT jdbcpoc.cfapps.io - [2018-10-13T13:37:38.420+0000] "GET /delay?d1=5&d2=5 HTTP/1.1" 200 0 52 "-" "Apache-HttpClient/4.5.3 (Java/1.8.0_152)" "10.10.66.112:34148" "10.10.149.182:61070" x_forwarded_for:"24.11.122.135, 10.10.66.112" x_forwarded_proto:"http" vcap_request_id:"6e3ea3bb-0aec-45a8-7dde-28769df154bb" response_time:5.550970918 app_id:"94d62bb6-bcdd-4f80-b701-37b1cee68def" app_index:"0" x_b3_traceid:"d207aeb6f14a8995" x_b3_spanid:"d207aeb6f14a8995" x_b3_parentspanid:"-"
   2018-10-13T07:37:43.97-0600 [RTR/1] OUT 
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:142)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator$1$1.run(AbstractCommand.java:1154)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable$1.call(HystrixContextRunnable.java:45)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable$1.call(HystrixContextRunnable.java:41)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable.run(HystrixContextRunnable.java:61)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator$1.tick(AbstractCommand.java:1159)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.util.HystrixTimer$1.run(HystrixTimer.java:99)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at java.lang.Thread.run(Thread.java:748)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR Caused by: java.util.concurrent.TimeoutException
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand.handleTimeoutViaFallback(AbstractCommand.java:997)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand.access$500(AbstractCommand.java:60)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$12.call(AbstractCommand.java:610)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$12.call(AbstractCommand.java:601)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:140)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	... 15 more
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR com.netflix.hystrix.exception.HystrixRuntimeException: primaryCall timed-out and fallback failed.
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$22.call(AbstractCommand.java:825)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$22.call(AbstractCommand.java:804)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:140)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$DeprecatedOnFallbackHookApplication$1.onError(AbstractCommand.java:1472)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$FallbackHookApplication$1.onError(AbstractCommand.java:1397)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at rx.observers.Subscribers$5.onError(Subscribers.java:230)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:44)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:28)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   2018-10-13T07:37:43.97-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   2018-10-13T07:37:43.97-0600 [RTR/7] OUT jdbcpoc.cfapps.io - [2018-10-13T13:37:38.419+0000] "GET /delay?d1=5&d2=5 HTTP/1.1" 200 0 52 "-" "Apache-HttpClient/4.5.3 (Java/1.8.0_152)" "10.10.66.112:27326" "10.10.149.182:61070" x_forwarded_for:"24.11.122.135, 10.10.66.112" x_forwarded_proto:"http" vcap_request_id:"1bd611bd-e6cd-4214-6aa2-255df4151ef0" response_time:5.559564577 app_id:"94d62bb6-bcdd-4f80-b701-37b1cee68def" app_index:"0" x_b3_traceid:"9bdec53db20262a5" x_b3_spanid:"9bdec53db20262a5" x_b3_parentspanid:"-"
   2018-10-13T07:37:43.97-0600 [RTR/7] OUT 
   2018-10-13T07:37:43.98-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   2018-10-13T07:37:43.98-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   2018-10-13T07:37:43.98-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   2018-10-13T07:37:43.98-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   2018-10-13T07:37:43.98-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:43.98-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   2018-10-13T07:37:43.98-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   2018-10-13T07:37:43.98-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:43.98-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   2018-10-13T07:37:43.98-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   2018-10-13T07:37:43.98-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   2018-10-13T07:37:43.98-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   2018-10-13T07:37:43.98-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:43.98-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   2018-10-13T07:37:43.98-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   2018-10-13T07:37:43.98-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   2018-10-13T07:37:43.98-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   2018-10-13T07:37:43.98-0600 [APP/PROC/WEB/0] ERR 	at rx.Observable.unsafeSubscribe(Observable.java:10151)
   2018-10-13T07:37:43.98-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:142)
   2018-10-13T07:37:43.98-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:43.98-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   2018-10-13T07:37:43.98-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator$1$1.run(AbstractCommand.java:1154)
   2018-10-13T07:37:43.98-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable$1.call(HystrixContextRunnable.java:45)
   2018-10-13T07:37:43.98-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable$1.call(HystrixContextRunnable.java:41)
   2018-10-13T07:37:43.98-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable.run(HystrixContextRunnable.java:61)
   2018-10-13T07:37:43.98-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator$1.tick(AbstractCommand.java:1159)
   2018-10-13T07:37:43.98-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.util.HystrixTimer$1.run(HystrixTimer.java:99)
   2018-10-13T07:37:43.98-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
   2018-10-13T07:37:43.98-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
   2018-10-13T07:37:43.98-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
   2018-10-13T07:37:43.98-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
   2018-10-13T07:37:43.98-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   2018-10-13T07:37:43.98-0600 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   2018-10-13T07:37:43.98-0600 [APP/PROC/WEB/0] ERR 	at java.lang.Thread.run(Thread.java:748)
   2018-10-13T07:37:43.99-0600 [RTR/5] OUT jdbcpoc.cfapps.io - [2018-10-13T13:37:38.416+0000] "GET /delay?d1=5&d2=5 HTTP/1.1" 200 0 52 "-" "Apache-HttpClient/4.5.3 (Java/1.8.0_152)" "10.10.66.112:63536" "10.10.149.182:61070" x_forwarded_for:"24.11.122.135, 10.10.66.112" x_forwarded_proto:"http" vcap_request_id:"74d52cf8-c679-4a0d-5dcc-87fc7f4ef94e" response_time:5.575506898 app_id:"94d62bb6-bcdd-4f80-b701-37b1cee68def" app_index:"0" x_b3_traceid:"06d93aadf65e502d" x_b3_spanid:"06d93aadf65e502d" x_b3_parentspanid:"-"
   2018-10-13T07:37:43.99-0600 [RTR/5] OUT 
   2018-10-13T07:37:43.99-0600 [APP/PROC/WEB/0] ERR Caused by: java.util.concurrent.TimeoutException
   2018-10-13T07:37:43.99-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand.handleTimeoutViaFallback(AbstractCommand.java:997)
   2018-10-13T07:37:43.99-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand.access$500(AbstractCommand.java:60)
   2018-10-13T07:37:43.99-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$12.call(AbstractCommand.java:610)
   2018-10-13T07:37:43.99-0600 [APP/PROC/WEB/0] ERR 	at com.netflix.hystrix.AbstractCommand$12.call(AbstractCommand.java:601)
   2018-10-13T07:37:43.99-0600 [APP/PROC/WEB/0] ERR 	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:140)
   2018-10-13T07:37:43.99-0600 [APP/PROC/WEB/0] ERR 	... 15 more
